- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
     - name: Provision a set of instances
       ec2:
         ec2_region: us-east-1
         key_name: winston
         group: service
         
         instance_type: t2.micro
         image: "ami-2d39803a"
         wait: true
         instance_tags:
            Name: test
         count_tag: Name
         exact_count: 1
       register: ec2
        
     - name: Add new instance to host group
       add_host: hostname={{ item.public_ip }} groupname=compucorp-ec2 ansible_user=ubuntu ansible_ssh_private_key_file=/home/winston/Sysadmin/winston.pem
       with_items: '{{ec2.instances}}'

 
     - name: Wait for SSH
       wait_for: host={{ item.public_dns_name}} port=22 delay=60 timeout=320 state=started
       with_items: '{{ec2.instances}}'
  
- name: Install services
  hosts: all
  become: True
  gather_facts: True
  vars_files:
    - group_vars/all.yml
    - group_vars/mysql_private.yml

  pre_tasks:
    - name: upgrade packages
      apt: upgrade=yes update_cache=yes cache_valid_time=300
      become: True
  roles:
  - dependencies
  - hostname
  - openssh
  - nginx
  - php-fpm
  - geerlingguy.mysql
  - site
