--- 
- name: Install nginx
  hosts: compucorp
  become_method: sudo
  become: yes
  become_user: root
  vars_files:
    - group_vars/all.yml
    - group_vars/mysql_private.yml
 
  pre_tasks:
    - name: upgrade packages
      apt: upgrade=yes update_cache=yes cache_valid_time=300
      sudo: yes
 
  roles: 
   - hostname
   - dependencies
   - nginx
   - php-fpm
   - geerlingguy.mysql
   - site

  #tasks:
  #  - hostname: {{server_hostname}}

